service: lambda-microservice-template

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10

package:
  individually: true

functions:
  first:
    handler: functions/first.default
    events:
      - http:
          method: GET
          path: first
  second:
    handler: second.default
    events:
      - http:
          method: GET
          path: second
